# Generated by Django 5.0.4 on 2024-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_floor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Qavat va Honalar', 'verbose_name_plural': 'Qavat va Honalar'},
        ),
    ]
