# Generated by Django 5.0.4 on 2024-05-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_floor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.floor', verbose_name='Qavat'),
        ),
    ]
