# Generated by Django 5.0.6 on 2024-06-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_floor_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=50, verbose_name='Group status')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_apartments', to='common.floor', verbose_name='Apartment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apartments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
