# Generated by Django 5.0.6 on 2024-07-04 13:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userapartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 4, 18, 20, 59, 936252), verbose_name='Date')),
                ('is_available', models.BooleanField(blank=True, null=True, verbose_name='Is available')),
                ('is_late', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.floor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
