# Generated by Django 5.0.6 on 2024-07-30 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_application_user_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 30, 18, 11, 53, 261977), verbose_name='Date'),
        ),
    ]
