# Generated by Django 5.1 on 2024-08-29 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 20, 44, 4, 521884), verbose_name='Date'),
        ),
    ]
