# Generated by Django 4.2.11 on 2024-08-29 16:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapartment',
            name='added_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapartment',
            name='deleted_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 21, 12, 42, 618379), verbose_name='Date'),
        ),
    ]
