# Generated by Django 4.2.11 on 2024-08-30 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_userapartment_added_at_userapartment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 20, 48, 52, 307079), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.floor', verbose_name='Qavat'),
        ),
        migrations.AlterField(
            model_name='userapartment',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
    ]
