# Generated by Django 4.2.11 on 2024-08-30 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0014_alter_attendance_date_alter_floor_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 20, 55, 16, 278135), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='StudentPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('student_apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='common.userapartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
