# Generated by Django 4.2.11 on 2024-08-30 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 21, 16, 33, 585376), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='studentpayments',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
