# Generated by Django 5.0.6 on 2024-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('owner', 'Owner'), ('student', 'Student')], default='employee', max_length=50, verbose_name='Type'),
        ),
    ]
